[0m13:43:25.633555 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f80e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070066d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107006cd0>]}


============================== 13:43:25.637280 | 7447fae5-292a-4db8-8dd8-efb8ddb56ed9 ==============================
[0m13:43:25.637280 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:43:25.637750 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/affanzafar/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt build', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:43:25.638190 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/affanzafar/Desktop/datawarehouse/dagster/ddd/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:43:25.640369 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.06840788, "process_in_blocks": "0", "process_kernel_time": 0.182751, "process_mem_max_rss": "102875136", "process_out_blocks": "0", "process_user_time": 1.02023}
[0m13:43:25.640723 [debug] [MainThread]: Command `dbt build` failed at 13:43:25.640639 after 0.07 seconds
[0m13:43:25.641035 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102b7d790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102ae6990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fc1590>]}
[0m13:43:25.641328 [debug] [MainThread]: Flushing usage events
[0m13:43:28.055182 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:44:00.999844 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107549b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10735fe90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1075ce9d0>]}


============================== 13:44:01.003516 | 96be97e6-11cd-4762-a015-2d481b89d69f ==============================
[0m13:44:01.003516 [info ] [MainThread]: Running with dbt=1.9.4
[0m13:44:01.003998 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/affanzafar/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt deps', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:44:01.004626 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/affanzafar/Desktop/datawarehouse/dagster/ddd/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:44:01.006900 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.06492404, "process_in_blocks": "0", "process_kernel_time": 0.167852, "process_mem_max_rss": "103645184", "process_out_blocks": "0", "process_user_time": 1.020792}
[0m13:44:01.007311 [debug] [MainThread]: Command `dbt deps` failed at 13:44:01.007223 after 0.07 seconds
[0m13:44:01.007644 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1032098d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1075eba10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1075eb590>]}
[0m13:44:01.007937 [debug] [MainThread]: Flushing usage events
[0m13:44:02.405746 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:48:28.717761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112447990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126b6850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126b7210>]}


============================== 11:48:28.721487 | 7796e9eb-59ca-4bc2-b839-9f1985ef61b8 ==============================
[0m11:48:28.721487 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:48:28.721955 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/affanzafar/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt build', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:48:28.722385 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/affanzafar/Desktop/datawarehouse/dagster/ddd/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:48:28.724573 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.06655442, "process_in_blocks": "0", "process_kernel_time": 0.175459, "process_mem_max_rss": "104153088", "process_out_blocks": "0", "process_user_time": 1.010017}
[0m11:48:28.724914 [debug] [MainThread]: Command `dbt build` failed at 11:48:28.724835 after 0.07 seconds
[0m11:48:28.725219 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1045a5790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104534e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112630050>]}
[0m11:48:28.725493 [debug] [MainThread]: Flushing usage events
[0m11:48:30.106953 [debug] [MainThread]: An error was encountered while trying to flush usage events
